# Generated by Django 2.1.2 on 2018-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedate', models.DateField(verbose_name='date published')),
                ('category', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
                ('subscribe', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('payment_logic', models.CharField(max_length=30)),
                ('etc', models.CharField(max_length=100)),
            ],
        ),
    ]
